/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GD;

import Test.QuanLiMain;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import quanlitrungtamngoaingu.GiangVien;
import quanlitrungtamngoaingu.HocVien;
import quanlitrungtamngoaingu.KhoaHoc;


public class fmKhoaHoc extends javax.swing.JFrame {
    private KhoaHoc kh = new KhoaHoc();
    /**
     * Creates new form fmKhoaHoc
     */
    public fmKhoaHoc(KhoaHoc kh) {
        initComponents();
        this.kh = kh;
        
        InTable();
        Inlist();
        HienthongtinKhoaHoc();
        ThongKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsgv = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHocVien = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKhoaHoc = new javax.swing.JTextArea();
        txtThongke = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        lsgv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lsgv);

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cập nhật Khóa Học");

        tbHocVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "Ngày Sinh", "Giới tính", "Quê quán", "CCCD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbHocVien.setRowHeight(35);
        jScrollPane2.setViewportView(tbHocVien);

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtKhoaHoc.setColumns(20);
        txtKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKhoaHoc.setRows(5);
        jScrollPane3.setViewportView(txtKhoaHoc);

        txtThongke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtThongke.setText("jLabel1");
        txtThongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(0, 65, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtThongke, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inlist(){
        DefaultListModel<String> model= new DefaultListModel<>();
        List<GiangVien> listgv = kh.getListgiangvien();
        for(var o : listgv){
            model.addElement(o.getTen() + " " + o.getSdt());
        }
        lsgv.setModel(model);
    }
    private void InTable(){
        List<HocVien>listH = kh.getListhocvien();
//        System.out.println(listH.size());
        Object data[][]= new Object[listH.size()][5];
        for(int i =0 ; i< listH.size(); i++){
            HocVien hocvien =listH.get(i);
            data[i][0]= hocvien.getTen();
            data[i][1]= hocvien.getNgaysinh();
            data[i][2]= hocvien.getGioitinh();
            data[i][3]=hocvien.getQue();
            data[i][4]=hocvien.getCccd();
        }
        String[] columnames= {"Tên","Ngày Sinh","Giới tính","Quê quán","CCCD"};
        DefaultTableModel model = new DefaultTableModel(data,columnames);
        tbHocVien.setModel(model);
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
    }//GEN-LAST:event_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String chucvu =JOptionPane.showInputDialog(null,"Nhập 1.Sửa học viên, 2. Sửa giảng viên",JOptionPane.PLAIN_MESSAGE);
        if(chucvu.equals("1")){
            String ten= JOptionPane.showInputDialog(null,"Nhập tên học viên cần sửa:",JOptionPane.PLAIN_MESSAGE);
            String tenlow= ten.toLowerCase();
            boolean found= false;
           List<HocVien> listhv= kh.getListhocvien();
           HocVien hv =new HocVien();
           for(HocVien o: listhv){
               String s= o.getTen().toLowerCase();
               if(s.equals(tenlow)){
                   hv=o;
                   found=true;
                   break;
               }
               
           }
           if(found){
              new NhapThongTin(kh,hv).setVisible(true);
              
              
           }else{
               JOptionPane.showMessageDialog(null,"Không tìm thấy học viên: "+ search.getText(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);
           }
        }else if(chucvu.equals("2")){
            String ten= JOptionPane.showInputDialog(null,"Nhập tên giảng viên cần sửa:",JOptionPane.PLAIN_MESSAGE);
            String tenlow= ten.toLowerCase();
           boolean found= false;
           List<GiangVien> listgv= kh.getListgiangvien();
           GiangVien gv =new GiangVien();
           for(GiangVien o: listgv){
               String s= o.getTen().toLowerCase();
               if(s.equals(tenlow)){
                   found=true;
                   gv =o;
                   break;
               }
               
           }
           if(found){
               new NhapThongTinGV(kh,gv).setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null, "Không tìm thấy giảng viên tên: "+search.getText(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);

           }
       }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
//        HocVien a = new HocVien();
        String chucvu =JOptionPane.showInputDialog(null,"Nhập 1.Thêm học viên, 2. Thêm giảng viên",JOptionPane.PLAIN_MESSAGE);
        if(chucvu.equals("1")){
            new NhapThongTin(kh).setVisible(true);
            this.dispose();
        }else if(chucvu.equals("2")){
            new NhapThongTinGV(kh).setVisible(true);
            this.dispose();
        }  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String ten = JOptionPane.showInputDialog(null,"Nhập 1.Xóa học viên, 2. Xóa giảng viên",JOptionPane.PLAIN_MESSAGE);
        if(ten.equals("1")){
            String tenn = JOptionPane.showInputDialog(null, "Nhập tên cần xóa:", "Xóa học viên", JOptionPane.PLAIN_MESSAGE);
            String tenlow= tenn.toLowerCase();
            if (tenn != null && !tenn.isEmpty()) {
                List<HocVien> hocVienList = kh.getListhocvien();
                Iterator<HocVien> iterator = hocVienList.iterator();
                boolean found = false; // Cờ để xác định xem có tìm thấy sinh viên hay không

                while (iterator.hasNext()) {
                    HocVien hocVien = iterator.next();
                    String s= hocVien.getTen().toLowerCase();
                    if (s.equals(tenlow)) {
                        iterator.remove();
                        found = true;
                    }
                }
                QuanLiMain.SaveData();

                if (found) {
                    // Cập nhật lại JTable hoặc model
                    DefaultTableModel model = (DefaultTableModel) tbHocVien.getModel();
                    model.setRowCount(0); // Xóa tất cả các dòng trong model

                    for (HocVien hocVien : hocVienList) {
                        Object[] row = {hocVien.getTen(), hocVien.getNgaysinh(), hocVien.getGioitinh(),hocVien.getQue(),hocVien.getCccd()};
                        model.addRow(row); // Thêm lại dữ liệu vào model
                    }
                } else {
                    // Hiển thị thông báo khi không tìm thấy sinh viên
                    JOptionPane.showMessageDialog(null, "Không tìm thấy học viên tên: " + tenn, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        
        }else if(ten.equals("2")){
            String tengv= JOptionPane.showInputDialog(null,"Nhập tên giảng viên cần xóa:",JOptionPane.PLAIN_MESSAGE);
            String tenlow =tengv.toLowerCase();
            if(tengv!=null && !tengv.isEmpty()){
                List<GiangVien> listgv= kh.getListgiangvien();
                Iterator<GiangVien> iterator =listgv.iterator();
                boolean found= false;
                while(iterator.hasNext()){
                    GiangVien giangvien =iterator.next();
                    String s= giangvien.getTen().toLowerCase();
                    if(s.equals(tenlow)){
                        iterator.remove();
                        found =true;
                    }
                }
                QuanLiMain.SaveData();
                if(found){
                    DefaultListModel model = (DefaultListModel) lsgv.getModel();
                    model.clear();
                    for(GiangVien o: listgv){
                        model.addElement(o.getTen()+" "+ o.getSdt());
                    }
                    lsgv.setModel(model);
                }else{
                    JOptionPane.showMessageDialog(null,"Không tìm thấy giảng viên"+ tengv,"Thông báo",JOptionPane.INFORMATION_MESSAGE);
                }
            }
           
            
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String ten= JOptionPane.showInputDialog(null,"Nhập 1.Tìm học viên, 2.Tìm Giảng viên",JOptionPane.PLAIN_MESSAGE);
       String tenlow= search.getText().toLowerCase();
       if(ten.equals("1")){
           boolean found= false;
           List<HocVien> listhv= kh.getListhocvien();
           HocVien hv =new HocVien();
           for(HocVien o: listhv){
               String s= o.getTen().toLowerCase();
               if(s.equals(tenlow)){
                   hv=o;
                   found=true;
                   break;
               }
               
           }
           if(found){
              
               JOptionPane.showMessageDialog(null,"Thông tin học viên :"+hv.toString(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(null,"Không tìm thấy học viên: "+ search.getText(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);
           }
       }else if(ten.equals("2")){
           boolean found= false;
           List<GiangVien> listgv= kh.getListgiangvien();
           GiangVien gv =new GiangVien();
           for(GiangVien o: listgv){
               String s= o.getTen().toLowerCase();
               if(s.equals(tenlow)){
                   found=true;
                   gv =o;
                   break;
               }
               
           }
           if(found){
               JOptionPane.showMessageDialog(null,"Thông tin giảng viên :"+gv.toString(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(null, "Không tìm thấy giảng viên tên: "+search.getText(),"Thông báo",JOptionPane.INFORMATION_MESSAGE);

           }
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void HienthongtinKhoaHoc(){
        String t= kh.toString();
        txtKhoaHoc.setText(t);
        
    }
    private void ThongKe(){
        long tien= kh.getGia()*kh.getListhocvien().size();
        String s= "Doanh thu khóa học: "+String.valueOf(tien);
        txtThongke.setText(s);
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(fmKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(fmKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(fmKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(fmKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new fmKhoaHoc().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lsgv;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbHocVien;
    private javax.swing.JTextArea txtKhoaHoc;
    private javax.swing.JLabel txtThongke;
    // End of variables declaration//GEN-END:variables
}
